CREATE TABLE TB_JDBC_BOARD("BOARD_NO" NUMBER, "TITLE" VARCHAR2(40), "CONTENT" VARCHAR2(40), "USER_ID" VARCHAR2(40), "REG_DATE" DATE);
SELECT *
FROM TB_JDBC_BOARD;
DELETE TB_JDBC_BOARD;
SELECT NVL(MAX(BOARD_NO),0) + 1 FROM TB_JDBC_BOARD;

commit;
Update TB_JDBC_BOARD Set title = 'dd', content = 'ss' WHERE BOARD_NO IN 1